version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      IPFS_URL: http://ipfs:5001
    depends_on:
      ipfs:
        condition: service_healthy

  ipfs:
    image: ipfs/go-ipfs
    ports:
      - "5001:5001"
      - "8080:8080"
    environment:
      IPFS_PROFILE: "server"
    volumes:
      - ipfs_data:/data/ipfs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  ipfs_data:
